# Generated by Django 3.0.7 on 2020-11-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sample', models.TextField(db_column='SAMPLE', primary_key=True, serialize=False)),
                ('humidity', models.IntegerField(db_column='HUMIDITY')),
                ('temperature', models.IntegerField(db_column='TEMPERATURE')),
            ],
            options={
                'db_table': 'SENSOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensordata',
            fields=[
                ('sampleindex', models.AutoField(db_column='SAMPLEINDEX', primary_key=True, serialize=False)),
                ('humidity', models.IntegerField(db_column='HUMIDITY')),
                ('temperature', models.IntegerField(db_column='TEMPERATURE')),
            ],
            options={
                'db_table': 'SENSORDATA',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
