# Generated by Django 3.0.7 on 2020-11-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sensor', '0003_auto_20201117_0549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.AlterModelTable(
            name='sensordata',
            table=None,
        ),
    ]
