# Generated by Django 3.0.7 on 2020-11-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sensor', '0002_auto_20201117_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={},
        ),
    ]
