# Generated by Django 3.1.3 on 2020-12-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensordata',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('humidity', models.IntegerField()),
                ('temperature', models.IntegerField()),
            ],
            options={
                'db_table': 'SENSORDATA',
                'managed': False,
            },
        ),
    ]
